version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: notes-postgres-home-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: notes_password
      POSTGRES_DB: notes_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: